### ISSUE TITLE
coomunity

### ISSUE THREAD

**Issue by rami-dabain** [neutroncoin/neutron#17]
Maybe post some link to community/forum where you can interchange iedas and things with your coin holders?
wanted to download the wallet to start a MN, but hey 3% dev fee of what? mining? MNs ? tx ?

**Comment by ndembezeh** [comment]
I am using the following to setup a MN “Neutron v2.0.0 GUI Ubuntu MN Setup EASY” installation guide (https://steemit.com/neutron/@oicu8/neutron-v2-0-0-ubuntu-mn-setup-easy). After installing, rebooting and login in as root, when I Open Neutron Wallet icon on the desktop I have the following error message; “Error initializing database environment /root/.neutron! To recover, BACKUP THAT DIRECTORY, then remove everything from it except for wallet.dat.”
I couldn’t follow the recommendation above because wallet.dat doesn’t exit. Can someone help me with this error please?

**Comment by oicu8** [comment]
We have update our website, https://www.neutroncoin.com/ 
Our White Paper is also on our website that includes everything needed to know.

For Support Please Visit https://www.neutroncoin.com/support/ for help with installation. Thanks!
