### ISSUE TITLE
Staking destroys MN Collateral

### ISSUE THREAD

**Issue by Bamboo4Panda** [neutroncoin/neutron#32]
Staking should not use any collateral input defined in masternode.conf, currently any masternode must use staking=0 as otherwise collateral tx will be altered upon staking.

**Comment by oicu8** [comment]
Neutron by Default is a Staking Coin which uses **"staking=1"** unless otherwise defined in the **"neutron.conf"** 

If running a Masternode, Please **DISABLE** Staking by adding **"staking=0"** in the **"neutron.conf".** 

A Future Update will contain **Individual TX locking/Coin locking** which will stop this. 
Please watch for updates. 

Thanks for your Comment, Loyalty, and Continued Support. 
Closing Issue.

Example of Upcoming "**Locking unspent**"
![image](https://user-images.githubusercontent.com/34317311/58602743-9843fe00-8253-11e9-9798-24e2f733f223.png)

**Oicu8**
**Neutron Core Team**
[https://www.neutroncoin.com/support](https://www.neutroncoin.com/support)

**Comment by barrystyle** [comment]
This indicates that AvailableCoins is not recognising the collateral amount
correctly; nothing special required other than nCoinType/mapWallet fixes.

 

baz

 

  _____
